# ~/.config/foot/foot.ini

[main]
term=xterm-256color
pad=10x10
font=Source Code Pro:size=19
bold-text-in-bright=yes

[cursor]
style=block
blink=yes

[colors-dark]
alpha=0.85
background=101113
foreground=d8d0c8

cursor=080b0f f2a15d

selection-background=1a2232
selection-foreground=f4eee6

regular0=080b0f
regular1=6b2321
regular2=3f5146
regular3=8d7147
regular4=1a2232
regular5=4f3c58
regular6=2b4f5d
regular7=d8d0c8

bright0=df5232
bright1=9e3b2d
bright2=5e7668
bright3=e3b572
bright4=2a3650
bright5=7a5c8a
bright6=4c7a8a
bright7=f4eee6
