# ~/.config/foot/foot.ini

[main]
term=xterm-256color
pad=10x10
font=Source Code Pro:size=16
bold-text-in-bright=yes

[cursor]
style=block
blink=yes

[colors-dark]
alpha=1
background=0b0708
foreground=d8d0c8

cursor=0b0708 c44f3b

selection-background=982922
selection-foreground=f4eee6

regular0=0b0708
regular1=6b2321
regular2=3f5146
regular3=8d7147
regular4=982922
regular5=703641
regular6=5c1b1b
regular7=d8d0c8

bright0=df5232
bright1=9e3b2d
bright2=5e7668
bright3=e3b572
bright4=c44f3b
bright5=e98c6e
bright6=f2a15d
bright7=f4eee6

[key-bindings]
unicode-input=none
# Helix-like scrollback navigation on the home row.
scrollback-up-line=Control+k
scrollback-down-line=Alt+j
scrollback-home=Alt+g
scrollback-end=Alt+e
