general {
    hide_cursor = true
    grace = 2
    immediate_render = false
    fractional_scaling = 2
}

auth {
    pam {
        enabled = true
        module = hyprlock
    }
}

animations {
    enabled = true

    bezier = outQuint, 0.23, 1, 0.32, 1
    bezier = soft, 0.20, 0.00, 0.00, 1.00

    # bardziej widoczne wejście, ale dalej minimalistyczne
    animation = fade, 1, 4.5, outQuint
    animation = inputFieldFade, 1, 2.4, soft
    animation = inputFieldDots, 1, 1.8, soft
}

background {
    monitor =
    path = screenshot
    color = rgba(8, 11, 15, 1.0)

    # mniejszy blur niż wcześniej
    blur_passes = 2
    blur_size = 4
    noise = 0.008
    contrast = 0.90
    brightness = 0.84
    vibrancy = 0.10
    vibrancy_darkness = 0.06
}

# subtelny, ciepły panel bez ramki
shape {
    monitor =
    size = 760, 250
    color = rgba(20, 16, 15, 0.25)
    rounding = 24

    # ramka całego locka
    border_size = 2
    border_color = rgba(242, 161, 93, 0.72)

    position = 0, 12
    halign = center
    valign = center

    shadow_passes = 1
    shadow_size = 6
    shadow_boost = 1.08
    shadow_color = rgba(0, 0, 0, 0.24)
}
label {
    monitor =
    text = $TIME
    color = rgba(244, 238, 230, 1.0)
    font_size = 82
    font_family = Source Code Pro

    position = 0, 85
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %d %B')"
    color = rgba(216, 208, 200, 0.80)
    font_size = 20
    font_family = Source Code Pro

    position = 0, 22
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 580, 96

    # bez ramki pola hasła
    outline_thickness = 0
   # outer_color = rgba(0, 0, 0, 0.0)

    # bardziej stapia się z panelem, nie odcina się od blur
    inner_color = rgba(20, 16, 15, 0)

    check_color = rgba(242, 161, 93, 0.95)
    fail_color = rgba(196, 79, 59, 0.95)

    font_color = rgba(244, 238, 230, 1.0)
    font_family = Source Code Pro

    # bez "hasło..."
    placeholder_text = 
    fail_text = <span foreground="##f4eee6">$FAIL</span>

    dots_center = true
    dots_size = 0.38
    dots_spacing = 0.36
    dots_rounding = -1

    fade_on_empty = false
    rounding = 24
    hide_input = false

    position = 0, -50
    halign = center
    valign = center

    shadow_passes = 0
    shadow_size = 0
}
