general {
  grab_focus = true
}

cache {
  enabled = false
}

finders {
  default_finder = desktop
  desktop_icons = true

  # zostaw defaulty, ale daję komplet:
  desktop_prefix =
  unicode_prefix = .
  math_prefix = =
  font_prefix = '
}

ui {
  window_size = 560 340
}
