background = 0xE6080B0F      # sadza, lekka mgła (zostaje)
base = 0xFF14100F            # ciepły węgiel (zamiast zimnego granatu)
alternate_base = 0xFF1C1412  # hover/alt, nadal ciepłe

text = 0xFFD8D0C8            # kościany tekst (spójne z foot)
bright_text = 0xFFF4EEE6

accent = 0xFFF2A15D          # ember / płomień (ramka/focus)
accent_secondary = 0xFFDF5232 # rdza/ognisty czerwony (drugie akcenty)

rounding_large = 8
rounding_small = 4

icon_theme = Papirus-Dark
