background = 0xE60F0B0C      # sadza z lekką czerwienią z tapety
base = 0xFF191314            # głęboki węgiel z ciemnych partii płomieni
alternate_base = 0xFF221416  # cieplejszy alt/hover

text = 0xFFD8D0C8            # kościany tekst (spójne z foot)
bright_text = 0xFFF4EEE6

accent = 0xFFF2A15D          # ember / płomień (ramka/focus)
accent_secondary = 0xFFC44F3B # rdza z centrum tapety

rounding_large = 8
rounding_small = 4

icon_theme = Papirus-Dark
