source = ~/.config/hypr/env.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/look_and_feel.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/keys.conf
source = ~/.config/hypr/start_programs.conf
