windowrule = opacity 1.00 0.95, match:class ^(foot)$



windowrule {
    name = dash-spotatui
    match:class = ^(spotatui)$

    workspace = 1 silent
    float = yes

    # duże okno po lewej
    size = 1500 950
    move = 40 85
}

windowrule {
    name = dash-cava
    match:class = ^(cava)$

    workspace = 1 silent
    float = yes

    # mniejsze okno po prawej na dole (jak na screenie)
    size = 1100 520
    move = monitor_w-1100-40 monitor_h-520-70
}

#Example windowrules that are useful
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
