[opener]
edit = [
  { run = "helix %s", block = true, for = "linux", desc = "Edit in Helix" },
]

rstudio = [
  { run = 'gio launch "/usr/share/applications/rstudio.desktop" "%s1"', orphan = true, for = "linux", desc = "Open in RStudio" },
]

[open]
prepend_rules = [
  # R / RMarkdown / R project -> RStudio
  { url = "*.r", use = "rstudio" },
  { url = "*.rmd", use = "rstudio" },
  { url = "*.rproj", use = "rstudio" },

  # ogólnie tekst
  { mime = "text/*", use = "edit" },

  # rzeczy, które czasem nie wpadają jako text/*
  { url = "*.rs", use = "edit" },
  { url = "*.toml", use = "edit" },
  { url = "*.json", use = "edit" },
  { url = "*.yml", use = "edit" },
  { url = "*.yaml", use = "edit" },
  { url = "*.conf", use = "edit" },
  { url = "*.ini", use = "edit" },
  { url = "*.sh", use = "edit" },
]
